services:
  api:
    build: .
    container_name: cereal-api
    ports:
      - "5556:5556"   # Docker API port
    volumes:
      - ./CerealAPI/Data:/app/Data
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=cerealdb;User=root;Password=123456;
      - ASPNETCORE_URLS=http://+:5556
      - DOTNET_ENVIRONMENT=Development
    restart: always

  db:
    image: mysql:8.0.43
    container_name: cereal-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cerealdb
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"   # Docker MySQL port
    volumes:
      - cereal-mysql-data:/var/lib/mysql
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api
      - db

volumes:
  cereal-mysql-data:
  jenkins_home:
