version: '3.9'

services:
  api:
    build: .
    container_name: cereal-api
    ports:
      - "5556:5556"   # Docker API port
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=DATABASE NAME;User=USERNAME;Password=PASSWORD;
      - ASPNETCORE_URLS=http://+:5556
      - DOTNET_ENVIRONMENT=Development
    restart: always

  db:
    image: mysql:8.0.43
    container_name: cereal-db
    environment:
      MYSQL_ROOT_PASSWORD: DockerizedPasswordHere
      MYSQL_DATABASE: CerealDB
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"   # Docker MySQL port
    volumes:
      - cereal-mysql-data:/var/lib/mysql
    restart: always

volumes:
  cereal-mysql-data:
